In [6]:
import pandas as pd

df = pd.read_csv('data/iris.csv')


display(df.head())


display(df.tail())


print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("Data Types:\n", df.dtypes)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

Shape: (150, 5)
Columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
Data Types:
 sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In this cell, we imported the pandas library and read the contents of the CSV file into a DataFrame named `df`.

In [7]:

print("Missing values per column:\n", df.isnull().sum())


print("Duplicate rows count:", df.duplicated().sum())


print("Unique species count:", df['species'].nunique())
print("Flower count per species:\n", df['species'].value_counts())


print("Average Sepal Length:", round(df['sepal_length'].mean(), 2))
print("Maximum Petal Length:", df['petal_length'].max())
print("Minimum Sepal Width:", df['sepal_width'].min())

# Groupby mean calculation
species_summary = df.groupby('species').mean(numeric_only=True)
display(species_summary)


display(df.describe())

Missing values per column:
 sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64
Duplicate rows count: 1
Unique species count: 3
Flower count per species:
 species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
Average Sepal Length: 5.84
Maximum Petal Length: 6.9
Minimum Sepal Width: 2.0

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In this cell, we imported the pandas library as `pd` and loaded the Iris dataset from `data/iris.csv` into a DataFrame named `df`.

In [8]:

filtered_sepal = df[df['sepal_length'] > 6]
filtered_petal = df[df['petal_width'] > 1.5]
setosa_df = df[df['species'] == 'setosa']

display(filtered_sepal.head())
display(filtered_petal.head())
display(setosa_df.head())


highest_petal_species = df.groupby('species')['petal_length'].mean().idxmax()
print("Species with highest average petal length:", highest_petal_species)


sorted_df = df.sort_values(by='sepal_length', ascending=False)
display(sorted_df.head())

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
56           6.3          3.3           4.7          1.6  versicolor

    sepal_length  sepal_width  petal_length  petal_width     species
56           6.3          3.3           4.7          1.6  versicolor
70           5.9          3.2           4.8          1.8  versicolor
77           6.7          3.0           5.0          1.7  versicolor
83           6.0          2.7           5.1          1.6  versicolor
85           6.0          3.4           4.5          1.6  versicolor

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Species with highest average petal length: virginica

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica

# Data Filtering, Aggregation, and Sorting

In this section, we process and extract specific insights from the Iris dataset using boolean indexing, grouping, and sorting operations:

1. **Dataset Filtering (Boolean Indexing):**
   - **`filtered_sepal`**: Filters rows where `sepal_length` is greater than 6.0.
   - **`filtered_petal`**: Filters rows where `petal_width` is greater than 1.5.
   - **`setosa_df`**: Extracts all records belonging strictly to the `setosa` species.
   - We display the first 5 rows of each filtered subset using `.head()`.

2. **Group-Based Aggregation:**
   - We group the dataset by `species` and calculate the average `petal_length` for each group.
   - We use the `.idxmax()` function to return the specific species name (`virginica`) that holds the highest average petal length.

3. **Data Sorting:**
   - We sort the entire dataset based on `sepal_length` in descending order using `sort_values(by='sepal_length', ascending=False)`.
   - We display the top 5 rows of the sorted DataFrame.

In [9]:
import os


os.makedirs('output', exist_ok=True)


species_summary.to_csv('output/species_summary.csv')
filtered_sepal.to_csv('output/filtered_iris.csv', index=False)

print("Files successfully exported to output directory.")

Files successfully exported to output directory.

# Exporting Analysis Results to CSV

In this section, we save the summarized metrics and filtered data into output CSV files for future use and reporting:

1. **Creating Output Directory:**
   - We use `os.makedirs('output', exist_ok=True)` to create an `output/` folder if it does not already exist. The `exist_ok=True` parameter prevents errors if the directory already exists.

2. **Exporting Grouped Summary Data:**
   - We export the `species_summary` DataFrame to `output/species_summary.csv` using the `.to_csv()` function, preserving the species names as index labels.

3. **Exporting Filtered Data:**
   - We save the `filtered_sepal` DataFrame to `output/filtered_iris.csv`. The `index=False` parameter is used to avoid writing row index numbers into the file.

4. **Confirmation:**
   - A confirmation message is printed to verify that all files were exported successfully.